export const testPeople = [
  {
    first_name: "Amitabh",
    middle_name: "Rajendra",
    last_name: "Shah",
    father_full_name: "Rajendra Mohan Shah",
    dob: "03-02-1990",
    gender: "Male",
    phone_number: "9876543210",
    email: "amit.shah@gmail.com",
    aadhar_number: "1234 5678 9012",
    address: "15th Floor, Bandra West, Mumbai",
    // pan_number: "ABCDE1234F",
    verified: true,
    current_employer: '07AAGXXXXX4N1Z1',
    current_role: 'Chef',
    recommends: [{ employer: '07AAGXXXXX4N1Z1', message: "Innovative cooking" }],
  },
  {
    first_name: "Priya",
    middle_name: "Rakesh",
    last_name: "Singh",
    father_full_name: "Rakesh Rajiv Singh",
    dob: "08-11-1988",
    gender: "Female",
    phone_number: "9988776655",
    email: "priya.singh@yahoo.com",
    aadhar_number: "2345 6789 0123",
    address: "3rd Floor, Hinjewadi, Pune",
    // pan_number: "BCDEF2345G",
    verified: true,
    current_employer: '07AAGXXXXX4N1Z1',
    current_role: 'Assistant Chef',
    recommends: [{ employer: '07AAGXXXXX4N1Z1', message: "Cooperative" }],
  },
  {
    first_name: "Raj",
    middle_name: "Prakash",
    last_name: "Patil",
    father_full_name: "Prakash Sunil Patil",
    dob: "17-07-1995",
    gender: "Male",
    phone_number: "8976543210",
    email: "raj.patil@hotmail.com",
    aadhar_number: "3456 7890 1234",
    address: "5th Floor, Kandivali East, Mumbai",
    // pan_number: "CDEFG3456H",
    verified: true,
    current_employer: '07AAGXXXXX4N1Z1',
    current_role: 'Assistant Chef',
    recommends: [{ employer: '07AAGXXXXX4N1Z1', message: "Cooperative" }],
  },
  {
    first_name: "Sneha",
    middle_name: "Anil",
    last_name: "Gupta",
    father_full_name: "Anil Ankit Gupta",
    dob: "21-03-1992",
    gender: "Female",
    phone_number: "7890654321",
    email: "sneha.gupta@gmail.com",
    aadhar_number: "4567 8901 2345",
    address: "8th Floor, Aundh, Pune",
    // pan_number: "DEFGH4567I",
    verified: false,
  },
  {
    first_name: "Rahul",
    middle_name: "Amar",
    last_name: "Joshi",
    father_full_name: "Amar Prashant Joshi",
    dob: "12-06-1985",
    gender: "Male",
    phone_number: "9765432109",
    email: "rahul.joshi@yahoo.com",
    aadhar_number: "5678 9012 3456",
    address: "11th Floor, Worli, Mumbai",
    // pan_number: "EFGHI5678J",
    verified: true,
    current_employer: '07AAGXXXXX4N1Z1',
    current_role: 'Manager',
  },
  {
    first_name: "Kavya",
    middle_name: "Deepak",
    last_name: "Sharma",
    father_full_name: "Deepak Rakesh Sharma",
    dob: "19-09-1998",
    gender: "Female",
    phone_number: "9654321870",
    email: "kavya.sharma@hotmail.com",
    aadhar_number: "6789 0123 4567",
    address: "7th Floor, Wakad, Pune",
    // pan_number: "FGHIJ6789K",
    verified: true,
    past_employers: ['07AAGXXXXX4N1Z1'],
    reports: [{ flag: "orange", employer: '07AAGXXXXX4N1Z1', message: "Rude" }],
  },
  {
    first_name: "Ravi",
    middle_name: "Suresh",
    last_name: "Shinde",
    father_full_name: "Suresh Madhav Shinde",
    dob: "02-08-1987",
    gender: "Male",
    phone_number: "8765432109",
    email: "ravi.shinde@gmail.com",
    aadhar_number: "7890 1234 5678",
    address: "12th Floor, Powai, Mumbai",
    // pan_number: "KLMNO1234P",
    verified: true,
    past_employers: ['07AAGXXXXX4N1Z1'],
    reports: [{ flag: "red", employer: '07AAGXXXXX4N1Z1', message: "Offensive" }],
  },
  {
    first_name: "Arun",
    middle_name: "Sanjay",
    last_name: "Kulkarni",
    father_full_name: "Sanjay Mukund Kulkarni",
    dob: "15-11-1993",
    gender: "Male",
    phone_number: "7654321098",
    email: "arun.kulkarni@yahoo.com",
    aadhar_number: "8901 2345 6789",
    address: "2nd Floor, Magarpatta City, Pune",
    // pan_number: "LMNOP2345Q",
    current_employer: '07AAGXXXXX4N1Z1',
    current_role: 'Waiter',
    past_employers: ['07AAGXXXXX4N1Z1'],
    reports: [{ flag: "yellow", employer: '07AAGXXXXX4N1Z1', message: "Hospitality concern" }],
  },
  {
    first_name: "Neha",
    middle_name: "Manish",
    last_name: "Desai",
    father_full_name: "Manish Mukesh Desai",
    dob: "26-05-1997",
    gender: "Female",
    phone_number: "6543210987",
    email: "neha.desai@hotmail.com",
    aadhar_number: "9012 3456 7890",
    address: "6th Floor, Andheri West, Mumbai",
    // pan_number: "MNOPQ3456R",
    verified: true,
    current_employer: '27AAAFB4177D1ZR',
    current_role: 'Manager',
  },
  {
    first_name: "Vijay",
    middle_name: "Sachin",
    last_name: "More",
    father_full_name: "Sachin Girish More",
    dob: "11-04-1988",
    gender: "Male",
    phone_number: "5432109876",
    email: "vijay.more@gmail.com",
    aadhar_number: "0123 4567 8924",
    address: "9th Floor, Kothrud, Pune",
    // pan_number: "OPQRS4567T",
    verified: true,
    current_employer: '27AAAFB4177D1ZR',
    current_role: 'Chef',
  },
  {
    first_name: "Aarti",
    middle_name: "Nitin",
    last_name: "Sawant",
    father_full_name: "Nitin Rajan Sawant",
    dob: "22-01-1995",
    gender: "Female",
    phone_number: "4321098765",
    email: "aarti.sawant@yahoo.com",
    aadhar_number: "2345 6789 8123",
    address: "4th Floor, Malad East, Mumbai",
    // pan_number: "PQRST5678U",
    verified: true,
    current_employer: '27AAAFB4177D1ZR',
    current_role: 'Asst. Chef',
  },
  {
    first_name: "Smita",
    middle_name: "Anand",
    last_name: "Bose",
    father_full_name: "Anand Madhav Bose",
    dob: "24-09-1991",
    gender: "Female",
    phone_number: "9876123450",
    email: "smita.bose@gmail.com",
    aadhar_number: "0123 4567 8901",
    address: "9th Floor, Vashi, Mumbai",
    // pan_number: "OPQRST6789U",
    verified: true,
    past_employers: ['27AAAFB4177D1ZR'],
    reports: [{ flag: "red", employer: '27AAAFB4177D1ZR', message: "Offensive behavior" }],
  },
];


export const batch2 = [
  {
    first_name: "Rajesh",
    middle_name: "Kishore",
    last_name: "Rao",
    father_full_name: "Kishore Anil Rao",
    dob: "18-02-1994",
    gender: "Male",
    phone_number: "9654321078",
    email: "rajesh.rao@yahoo.com",
    aadhar_number: "1234 5678 9522",
    address: "4th Floor, Koregaon Park, Pune",
    // pan_number: "PQRST7890A",
    verified: true,
  },
  {
    first_name: "Anjali",
    middle_name: "Nilesh",
    last_name: "Patil",
    father_full_name: "Nilesh Dilip Patil",
    dob: "30-07-1996",
    gender: "Female",
    phone_number: "9876543102",
    email: "anjali.patil@hotmail.com",
    aadhar_number: "2345 6789 7123",
    address: "10th Floor, Pimpri, Pune",
    // pan_number: "QRSTU1234B",
    verified: true,
  },
  {
    first_name: "Rohan",
    middle_name: "Dinesh",
    last_name: "Thakur",
    father_full_name: "Dinesh Raj Thakur",
    dob: "11-12-1986",
    gender: "Male",
    phone_number: "8765432101",
    email: "rohan.thakur@gmail.com",
    aadhar_number: "3456 7890 1724",
    address: "7th Floor, Khar West, Mumbai",
    // pan_number: "RSTUV2345C",
    verified: true,
  },
  {
    first_name: "Neha",
    middle_name: "Ravi",
    last_name: "Gokhale",
    father_full_name: "Ravi Sunil Gokhale",
    dob: "19-06-1990",
    gender: "Female",
    phone_number: "7654321098",
    email: "neha.gokhale@yahoo.com",
    aadhar_number: "4597 2901 2345",
    address: "13th Floor, Mulund West, Mumbai",
    // pan_number: "STUVW3456D",
    verified: true,
  },
  {
    first_name: "Aakash",
    middle_name: "Rajesh",
    last_name: "Nair",
    father_full_name: "Rajesh Prasad Nair",
    dob: "25-01-1993",
    gender: "Male",
    phone_number: "6543210987",
    email: "aakash.nair@hotmail.com",
    aadhar_number: "5678 9012 8456",
    address: "5th Floor, Hinjewadi, Pune",
    // pan_number: "TUVWX4567E",
    verified: false,
  },

];

export const batch3 = [
  {
    first_name: "Tina",
    middle_name: "Nikhil",
    last_name: "Shah",
    father_full_name: "Nikhil Ramesh Shah",
    dob: "07-12-1993",
    gender: "Female",
    phone_number: "7654321098",
    email: "tina.shah@gmail.com",
    aadhar_number: "3456 7890 1234",
    address: "9th Floor, Khar West, Mumbai",
    // pan_number: "PQRST5678S",
  },
  {
    first_name: "Abhishek",
    middle_name: "Rahul",
    last_name: "Gupta",
    father_full_name: "Rahul Amit Gupta",
    dob: "12-01-1986",
    gender: "Male",
    phone_number: "9876543210",
    email: "abhishek.gupta@yahoo.com",
    aadhar_number: "4567 8901 2345",
    address: "4th Floor, Viman Nagar, Pune",
    // pan_number: "QRSTU6789T",
  },
  {
    first_name: "Simran",
    middle_name: "Rajesh",
    last_name: "Patil",
    father_full_name: "Rajesh Ramesh Patil",
    dob: "20-06-1991",
    gender: "Female",
    phone_number: "8765432109",
    email: "simran.patil@hotmail.com",
    aadhar_number: "5678 9012 7456",
    address: "11th Floor, Koregaon Park, Pune",
    // pan_number: "RSTUV7890U",
  },
  {
    first_name: "Sanjay",
    middle_name: "Amit",
    last_name: "Desai",
    father_full_name: "Amit Prakash Desai",
    dob: "22-09-1987",
    gender: "Male",
    phone_number: "6543210987",
    email: "sanjay.desai@gmail.com",
    aadhar_number: "6789 0123 4567",
    address: "13th Floor, Dadar West, Mumbai",
    // pan_number: "STUVW8901V",
  },
  {
    first_name: "Meera",
    middle_name: "Shankar",
    last_name: "Kulkarni",
    father_full_name: "Shankar Madhav Kulkarni",
    dob: "04-04-1995",
    gender: "Female",
    phone_number: "5432109876",
    email: "meera.kulkarni@yahoo.com",
    aadhar_number: "7890 1234 5678",
    address: "6th Floor, Baner, Pune",
    // pan_number: "TUVWX9012W",
  },
  {
    first_name: "Rohit",
    middle_name: "Anil",
    last_name: "Sharma",
    father_full_name: "Anil Ramesh Sharma",
    dob: "15-10-1989",
    gender: "Male",
    phone_number: "4321098765",
    email: "rohit.sharma@hotmail.com",
    aadhar_number: "9012 3456 7890",
    address: "16th Floor, Malad West, Mumbai",
    // pan_number: "UVWXY0123X",
  },
];

// console.log(testPeople.length);