import AppGrid from '@/components/AppGrid'
import Verify from '@/ocr/Verify'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>HRSpace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/datepicker.min.js"/>
      </Head>
      <Verify />
      <AppGrid />
      {/* <div> */}
        {/* Hello */}
        {/* <Navbar/>
        <Footer/> */}
      {/* </div> */}
      </>
  )
}
